;===========================================
;  Rainmeter configuration file
;===========================================

[Rainmeter]
Author=SH Lee
AppVersion=2.6
Update=200

[Metadata]
Name=[Iron_Man_HUD]CPU_Network
Version=0.92
License=Creative Commons Attribution-Non-Commercial-Share Alike
Information=Displaying CPU & Network status, Temp, Fan Speed

[Variables]
PI=3.14159
fontColor1=204,204,204,255
fontColor2=A0A0FF
rndcolor=E57733
strAngle1=0.506
strAngle2=-1.1519
strAngle3=-1.0472
rndAngle1=3.2149
rndAngle2=3.6128
ImageW=346
ImageH=10
Switch=0
Switch0=1
Switch1=0
;-----------------------------------------------------
; Caution : SpeedFan index numbers begin with 0
;-----------------------------------------------------
CPUTempIndex=6
GPUTempIndex=0

CPUFanIndex=0
AuxFanIndex=1

[Background]
Meter=IMAGE
ImageName=SysBG.png
X=0
Y=0

[Picture]
Meter=Image
ImageName=IronMan#Switch#.png
x=158
y=125
LeftMouseUpAction=[!SetVariable Switch1 #Switch#][!SetVariable Switch #Switch0#][!SetVariable Switch0 #Switch1#]
DynamicVariables=1

;==========================================================
;Displaying CPU temprature and Fan speed 
;You need to have SpeedFan running for this plugin to work
;http://www.almico.com/speedfan.php  <-- Official Page
;http://www.almico.com/speedfan449.exe <--- Download
;==========================================================

[MeasureCPUTemp]
Measure=Plugin
Plugin=Plugins\SpeedFanPlugin.dll
SpeedFanType=TEMPERATURE
SpeedFanNumber=#CPUTempIndex#
SpeedFanScale=C
Updatedivider=20

[MeasureCalcCPU]
Measure=Calc
Formula=MeasureCPUTemp/6.52+184

[MeasureGPUTemp]
Measure=Plugin
Plugin=Plugins\SpeedFanPlugin.dll
SpeedFanType=TEMPERATURE
SpeedFanNumber=#GPUTempIndex#
SpeedFanScale=C
Updatedivider=20

[MeasureCalcGPU]
Measure=Calc
Formula=MeasureGPUTemp/6.52+184

[MeasureCPUFan]
Measure=Plugin
Plugin=Plugins\SpeedFanPlugin.dll
SpeedFanType=FAN
SpeedFanNumber=#CPUFanIndex#
Updatedivider=20

[MeasureCalcCPUFan]
Measure=Calc
Formula=((MeasureCPUFan/200) % 360)+184
MaxValue=360

[MeasureSysFan]
Measure=Plugin
Plugin=Plugins\SpeedFanPlugin.dll
SpeedFanType=FAN
SpeedFanNumber=#AuxFanIndex#
Updatedivider=20

[MeasureCalcSysFan]
Measure=Calc
Formula=((MeasureSysFan/200) % 360)+184
MaxValue=360

;==================================================
; Display Temp & Speed
;==================================================
[MeterCPUTemp1]
Meter=String
MeasureName=MeasureCPUTemp
x=191
y=112
FontColor=#fontColor1#
FontSize=8
StringAlign=RightBottom
Angle=#strAngle1#
AntiAlias=1
Text=%1กษ 

[MeterCPUTemp2]
Meter=Roundline
MeasureName=MeasureCalcCPU
x=429
y=233
StartAngle=#rndAngle1#
RotationAngle=#rndAngle2#
LineLength=299
LineStart=286
LineColor=#rndColor#
Solid=1
ValueRemainder=184
AntiAlias=1

[MeterGPUTemp1]
Meter=String
MeasureName=MeasureGPUTemp
x=167
y=100
FontColor=#fontColor1#
FontSize=8
StringAlign=RightBottom
Angle=#strAngle1#
AntiAlias=1
Text=%1กษ 

[MeterGPUTemp2]
Meter=Roundline
MeasureName=MeasureCalcGPU
x=429
y=233
StartAngle=#rndAngle1#
RotationAngle=#rndAngle2#
LineLength=326
LineStart=312
LineColor=#rndColor#
Solid=1
ValueRemainder=184
AntiAlias=1


[MeterCPUFan]
Meter=String
MeasureName=MeasureCPUFan
x=130
y=78
FontColor=#fontColor2#
FontSize=8
StringAlign=RightBottom
Angle=#strAngle2#
AntiAlias=1
Text=%1rpm

[MeterCPUFan2]
Meter=Rotator
MeasureName=MeasureCalcCPUFan
ImageName=arrow1.png
x=256
y=60
OffsetX=0
OffsetY=(#ImageH# / 2)
W=(SQRT(#ImageW# ** 2 + #ImageH# ** 2))
H=(SQRT(#ImageW# ** 2 + #ImageH# ** 2))
AntiAlias=1


[MeterSysFan]
Meter=String
MeasureName=MeasureSysFan
x=113
y=72
FontColor=#fontColor2#
FontSize=8
StringAlign=RightBottom
Angle=#strAngle2#
AntiAlias=1
Text=%1rpm

[MeterSysFan2]
Meter=Rotator
MeasureName=MeasureCalcSysFan
ImageName=arrow2.png
x=256
y=60
OffsetX=0
OffsetY=(#ImageH# / 2)
W=(SQRT(#ImageW# ** 2 + #ImageH# ** 2))
H=(SQRT(#ImageW# ** 2 + #ImageH# ** 2))
AntiAlias=1

;=============================================
;CPU Status Bar Drawing
;=============================================

[MeasureCPUAll]
Measure=CPU
Processor=0

[mtCPU]
Meter=STRING
MeasureName=MeasureCPUAll
X=154
Y=221
FontColor=#fontColor1#
FontSize=8
StringAlign=Right
AntiAlias=1
NumOfDecimals=0
Text=%1 %

[msCPU]
Measure=Script
ScriptFile="#CURRENTPATH#cpu.lua"

[CPUBar1]
Meter=IMAGE
AntiAlias=1
ImageName=rest.png
x=0
y=0
ImageRotate=0
GradientAngle=150


[CPUBar2]
Meter=IMAGE
AntiAlias=1
ImageName=rest.png
x=0
y=-15r
ImageRotate=0

[CPUBar3]
Meter=IMAGE
ImageName=rest.png
x=0
y=-15r
ImageRotate=0

[CPUBar4]
Meter=IMAGE
ImageName=rest.png
x=0
y=-15r
ImageRotate=0

[CPUBar5]
Meter=IMAGE
ImageName=rest.png
x=0
y=-15r
ImageRotate=0

[CPUBar6]
Meter=IMAGE
ImageName=rest.png
x=0
y=-15r
ImageRotate=0

[CPUBar7]
Meter=IMAGE
ImageName=rest.png
x=0
y=-15r
ImageRotate=0

[CPUBar8]
Meter=IMAGE
ImageName=rest.png
x=0
y=-15r
ImageRotate=0

[CPUBar9]
Meter=IMAGE
ImageName=rest.png
x=0
y=-15r
ImageRotate=0

[CPUBar10]
Meter=IMAGE
ImageName=rest.png
x=0
y=-15r
ImageRotate=0

[CPUBar11]
Meter=IMAGE
ImageName=rest.png
x=0
y=-15r
ImageRotate=0

[CPUBar12]
Meter=IMAGE
ImageName=rest.png
x=0
y=-15r
ImageRotate=0

[CPUBar13]
Meter=IMAGE
ImageName=rest.png
x=0
y=-15r
ImageRotate=0

[CPUBar14]
Meter=IMAGE
ImageName=rest.png
x=0
y=-15r
ImageRotate=0

[CPUBar15]
Meter=IMAGE
ImageName=rest.png
x=0
y=-15r
ImageRotate=0

;=============================================
;Downloading Status Bar Drawing
;=============================================

[MeasureTcpIn]
Measure=NetIn

[mtTcpIn]
Meter=STRING
X=85
Y=221
FontColor=#fontColor2#
FontSize=7
StringAlign=Right
AntiAlias=1
Text=bps

[mtTcpIn1]
Meter=STRING
MeasureName=MeasureTcpIn
X=0r
Y=-8r
FontColor=#fontColor2#
FontSize=7
StringAlign=Right
AntiAlias=1
Text=%1

[msTcpIn]
Measure=Script
ScriptFile="#CURRENTPATH#graphin.lua"

[TcpInBar1]
Meter=IMAGE
AntiAlias=1
ImageName=inbar.png
x=0
y=100
ImageRotate=0
GradientAngle=150


[TcpInBar2]
Meter=IMAGE
AntiAlias=1
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar3]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar4]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar5]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar6]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar7]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar8]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar9]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar10]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar11]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar12]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar13]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar14]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar15]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar16]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar17]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar18]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar19]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar20]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar21]
Meter=IMAGE
AntiAlias=1
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar22]
Meter=IMAGE
AntiAlias=1
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar23]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar24]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar25]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar26]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar27]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar28]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar29]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

[TcpInBar30]
Meter=IMAGE
ImageName=inbar.png
x=0
y=-3r
ImageRotate=0

;=============================================
;Uploading Status Bar Drawing
;=============================================
[MeasureTcpOut]
Measure=NetOut

[mtTcpOut]
Meter=STRING
X=124
Y=221
FontColor=#fontColor2#
FontSize=7
StringAlign=Right
AntiAlias=1
Text=bps

[mtTcpOut1]
Meter=STRING
MeasureName=MeasureTcpOut
X=0r
Y=-8r
FontColor=#fontColor2#
FontSize=7
StringAlign=Right
AntiAlias=1
Text=%1

[msTcpOut]
Measure=Script
ScriptFile="#CURRENTPATH#graphout.lua"


[TcpOutBar1]
Meter=IMAGE
AntiAlias=1
ImageName=outbar.png
x=0
y=100
ImageRotate=0
GradientAngle=150


[TcpOutBar2]
Meter=IMAGE
AntiAlias=1
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar3]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar4]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar5]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar6]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar7]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar8]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar9]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar10]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar11]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar12]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar13]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar14]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar15]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar16]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar17]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar18]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar19]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar20]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar21]
Meter=IMAGE
AntiAlias=1
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar22]
Meter=IMAGE
AntiAlias=1
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar23]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar24]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar25]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar26]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar27]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar28]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar29]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

[TcpOutBar30]
Meter=IMAGE
ImageName=outbar.png
x=0
y=-3r
ImageRotate=0

